name: build
on: push
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get install musl-tools
    - run: make linux
    - uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: mongoose_linux
        tag: exe
        overwrite: true
  windows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make windows
    - uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: mongoose.exe
        tag: exe
        overwrite: true
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - run: make macos
    - uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: mongoose_macos
        tag: exe
        overwrite: true
